### ISSUE TITLE
Feature request: publish pre-built Android binaries as GitHub **Releases**

### ISSUE THREAD

**Issue by alfonsoalongi** [facebookexperimental/ExtendedAndroidTools#116]
#### Context
The repository already has CI workflows under `.github/workflows/`, notably:

* **bpftools.yml** – builds `bpftools` / `bpftools-min` for `arm64` and `x86_64`  
* **jdwp.yml** – builds the JDWP tracer  
* **black.yml** – linter

`bpftools.yml` even uploads the resulting `bpftools-<arch>.tar.gz` via  
`actions/upload-artifact@v4`.

That’s great 🎉 — but these artifacts are:

* **ephemeral** (default retention ≤ 90 days)  
* **hard to discover** (buried under each workflow run)  
* **not version-pinned** (no semantic tag or checksum)

---

#### Proposal

1. **Tag-triggered release**  
   Extend the existing workflow(s) to run on `push` **tags** (e.g. `v*`).  
2. **Attach artifacts as Release assets**  
   Use `softprops/action-gh-release` or `actions/create-release` + `upload-release-asset` to upload:  
   * `bpftools-arm64.tar.gz`  
   * `bpftools-x86_64.tar.gz`  
   * (optionally) `bpftools-min-*`, static `bpftrace` binaries, checksums  
3. **Release notes**  
   Auto-generate a note containing:  
   * commit hashes / submodule SHAs for *bcc*, *bpftrace*, *libbpf*, LLVM  
   * NDK version and key CMake flags (`STATIC_LINKING`, etc.)  
   * Minimum Android kernel / API requirement

---

#### Benefits

| For users | For maintainers |
|-----------|----------------|
| One-click download → `adb push` → done | Fewer “how do I build?” issues |
| Stable, permanent URLs for CI / Magisk modules | Reproducible bug reports tied to a tagged binary |
| Ability to bisect regressions across versions | Clear provenance of which LLVM/bcc revs shipped |

---

#### Minimal workflow tweak (illustrative)

```yaml
on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    uses: ./.github/workflows/bpftools.yml   # re-use current matrix
    secrets: inherit

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: { path: dist }
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/bpftools-*.tar.gz
````

This piggy-backs on the existing `make bpftools` logic; no code changes in `projects/` are required.

Thanks for considering!
Happy to open a PR with the workflow tweak if that helps.
